[package]
name = "jurand"
version = "1.3.1"
edition = "2021"
authors = ["Marián Konček <mkoncek@redhat.com>"]
repository = "https://github.com/fedora-java/jurand"
readme = "README.md"
license = "Apache-2.0"

[dependencies]
regex = "1.10"
walkdir = "2.4"
