name: Continuous Integration
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container: registry.access.redhat.com/ubi8:latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: dnf -y install gcc-c++ libasan libubsan
      - name: Compile
        run: |
          set -x
          CXX=g++
          CXXFLAGS+=' -g -D_GLIBCXX_ASSERTIONS -D_GLIBCXX_DEBUG'
          CXXFLAGS+=' -fsanitize=address,undefined'
          
          CXXFLAGS+=' -fconcepts'
          LDFLAGS+=' -lstdc++fs'
          
          export CXX
          export CXXFLAGS
          export LDFLAGS
          
          ./build.sh
      - name: Test
        run: ./test.sh
