name: Continuous Integration
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container: registry.access.redhat.com/ubi8:latest
    env:
      CXX: g++
      CXXFLAGS: -D_GLIBCXX_ASSERTIONS -D_GLIBCXX_DEBUG -pthread # -fsanitize=address,undefined
      LDFLAGS: -pthread # -fsanitize=address,undefined
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: dnf -y install diffutils gcc-toolset-12-gcc-c++ make libasan libubsan
      - name: Compile
        run: |
          source /opt/rh/gcc-toolset-12/enable
          make -j8 test-compile
      - name: Test
        run: |
          source /opt/rh/gcc-toolset-12/enable
          make test
