name: Continuous Integration
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container: registry.access.redhat.com/ubi8:latest
    env:
      CXX: g++
      CXXFLAGS: -fconcepts -D_GLIBCXX_ASSERTIONS -D_GLIBCXX_DEBUG -fsanitize=address,undefined
      LDFLAGS: -fsanitize=address,undefined
      LDLIBS: -lstdc++fs
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: dnf -y install diffutils gcc-c++ make libasan libubsan
      - name: Compile
        run: make -j8 test-compile
      - name: Test
        run: make test
