name: Continuous Integration
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container: quay.io/centos/centos:stream9
    env:
      CXX: g++
      CXXFLAGS: -D_GLIBCXX_ASSERTIONS -D_GLIBCXX_DEBUG -pthread -fsanitize=address,undefined
      LDFLAGS: -pthread -fsanitize=address,undefined
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          dnf -y install epel-release
          dnf -y install diffutils gcc-toolset-12-gcc-c++ gcc-toolset-12-libasan-devel gcc-toolset-12-libubsan-devel make rubygem-asciidoctor
      - name: Build manpages
        run: make -j8 manpages
      - name: Compile
        run: |
          source /opt/rh/gcc-toolset-12/enable
          make -j8 test-compile
      - name: Test
        run: |
          source /opt/rh/gcc-toolset-12/enable
          make test
